### ISSUE TITLE
Validation for ll/near is incorrect in venues if NW/SW bound are provided

### ISSUE THREAD

**Issue by kudrleon** [clintandrewhall/node-foursquare#18]
The application makes ll or near required, but the api would also work if only NE/SW is required. The condition in venues.search should be something like that:
  function search(lat, lng, near, params, accessToken, callback) {
    logger.enter('search');
    params = params || {};

   if(!lat || !lng) {
     if(!near) {
        if (!params.ne || !params.sw) {
               logger.error('Either lat and lng, near, or ne/sw are required as parameters.');
               callback(new Error('Venues.explore: near or ne/sw must be specified if lat and lng are not set.'));
               return;
            }
        } else {
           params.near = near;
        }
      } else {
         params.ll = lat + ',' + lng;
      }

```
logger.debug('search:lat: ' + lat);
logger.debug('search:lng: ' + lng);
logger.debug('search:near: ' + near);
logger.debug('search:params: ' + util.inspect(params));
core.callApi('/venues/search', accessToken, params, callback);
```

  }

**Comment by clintandrewhall** [comment]
This has been resolved by v0.4.1, by adding new methods for specific search styles.
