### ISSUE TITLE
getSuggestcompletion needs the argument near

### ISSUE THREAD

**Issue by beogip** [clintandrewhall/node-foursquare#24]
It's annoying that venues.getSuggestcompletion not allow the parameter near.
In the [foursquare api](https://developer.foursquare.com/docs/venues/suggestcompletion) is allowed

**Comment by brutaldev** [comment]
You can pass in `near` as a parameter property. Changing the function signature now to accept `near` as a passed in parameter (like the `search` function) would break backward compatibility.

The changes in pull request #26 will now allow you to pass in `null` lat/long values if you provide a `near` parameter property. The unit test for example passes it in like this:

```js
Foursquare.Venues.getSuggestcompletion(null, null, 'Baking', { near: 'Chicago' }, accessToken, 
function (error, data) {
});
```
