### ISSUE TITLE
getUser without parameters 

### ISSUE THREAD

**Issue by Exxplozer** [clintandrewhall/node-foursquare#25]
Function getUser haven't any parameters so I can't get self user because I can't add parameter 'v' for supported API version, I have got this error:
[Error: 410: The Foursquare API no longer supports requests that do not pass in a version parameter. For more details see https://developer.foursquare.com/overview/versioning]

**Comment by brutaldev** [comment]
You must provide the version globally in your config when you require `node-foursquare` and it will get sent in all API requests. Example:
```js
var foursquare = require('node-foursquare')({
    foursquare: {
      version: '20150802'
    }
  });
```
This is in the readme: https://github.com/clintandrewhall/node-foursquare#foursquare-api-version-and-deprecation-warnings

**Comment by clintandrewhall** [comment]
Thanks @brutaldev ...!
