### ISSUE TITLE
NSP/Snyke.io report of volunerability - upgrade of winston dependency

### ISSUE THREAD

**Issue by YasharF** [clintandrewhall/node-foursquare#30]
Snyk.io is reporting that node-foursquare depends on an out-of-date version of winston which is using a vulnerable version of request.  Winston as of version 0.8.0 no longer has a dependency on request.  Can you please upgrade node-foursquare to use a more updated version of winston?

**Comment by YasharF** [comment]
PR to fix this: https://github.com/clintandrewhall/node-foursquare/pull/31

**Comment by clintandrewhall** [comment]
This change has been made and added to v0.3.2
