### ISSUE TITLE
Changes to Foursquare API

### ISSUE THREAD

**Issue by YasharF** [clintandrewhall/node-foursquare#34]
**Source**: https://developer.foursquare.com/docs/announcements

Beginning on May 31st, Foursquare is making five changes in order to simplify their API and maintain the quality of their service as their developer community grows. These changes are:

1. The quantity of photos and tips per venue will be changed to 1 for Sandbox Tier and 2 Personal Tier
2. Access to check-in counts, visit counts, chain details, and key tastes will be removed
3. Venues search, explore, trending, similar, and next endpoints will return the following fields: venue name, venue ID, address, lat/long, and category. To access additional rich content for each venue, please call the details (venues/x) endpoint with venue ID as a parameter.
4. Regular endpoints will have a quota of 950 calls per day for Sandbox Tier and 99,500 calls per day for Personal Tier. Premium endpoints will have a quota of 50 calls per day for Sandbox Tier and 500 calls per day for Personal Tier. More info on our endpoints can be found here.
5. The caching time frame has been reduced to 24 hours. See here for more details.

======================

I suspect 2 might require some modification to this npm module.

**Comment by clintandrewhall** [comment]
This has been handled by v0.4.1... I'm considering adding some internal mechanism to track API calls and warn if limits are being approached.
