### ISSUE TITLE
No LTS versions of NodeJS 

### ISSUE THREAD

**Issue by YasharF** [clintandrewhall/node-foursquare#36]
Looks like that per https://github.com/clintandrewhall/node-foursquare/blob/master/package.json#L50 the package is no longer supporting any LTS versions of NodeJS.  I suggest making adjustments so at least the latest LTS version of NodeJS, currently 8.x is supported.  See https://github.com/nodejs/Release for the list of current versions of NodeJS, their support and LTS status.

Thank you

**Comment by clintandrewhall** [comment]
This has been resolved by v0.4.1
